databases:
  - name: budget_db
    databaseName: budget_db
    user: budget_db_3xsb_user

services:
  - type: web
    name: budget
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: budget_db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
